### ISSUE TITLE
Force update no longer working?

### ISSUE THREAD

**Issue by changer1198** [flashg1/TeslaSolarCharger#16] opened 2024-01-24 00:16 UTC
Anyone else having this issue as of yesterday?

The automation doesn't seem to run as the force update no longer works.

Reading around I can see others having similar issues. Something changed in the Tesla API for this?

**Comment by flashg1** [comment] 2024-01-26 03:47
As a temporary work-around, assign the "Wake up" button instead of the "Force data update" button in the blueprint, eg.

Tesla button force update Home Assistant:  Wake up

The value update to HA will be slower and hence the response by HA will be slower, but should still work.

The root cause of the issue was reported here,

https://github.com/alandtse/tesla/issues/830

**Comment by flashg1** [comment] 2024-05-09 11:36
"Force data update" button is working for me.  So staying with HACS Tesla version v3.20.4.

**Comment by flashg1** [comment] 2024-11-17 10:30
Closing case unless this is still an issue.

**Closed as completed by flashg1** 2024-11-17 10:30 UTC
